// Command refdata-snapshot regenerates deckard's embedded fallback copies of
// its refreshable reference datasets from the live public sources, using the
// same converters the running service uses:
//
//	internal/check/dns/takeover/fingerprints_community.yaml  (can-i-take-over-xyz)
//	internal/scope/shared_cidrs_snapshot.txt                 (Cloudflare, AWS CloudFront/GlobalAccelerator/S3, Fastly, GitHub Pages, Google)
//
// A scheduled CI job runs it (make refdata-snapshot) and opens a pull request
// when the files change. The hand-curated files (fingerprints.yaml,
// shared_cidrs.txt) are never touched.
//
// Flags:
//
//	-only takeover|shared|all   which dataset to regenerate (default all)
//	-takeover-out PATH          takeover snapshot file
//	-shared-out PATH            shared ranges snapshot file
//	-timeout DURATION           per-request timeout (default 30s)
//	-check                      write nothing; exit 1 if a file would change
//	-force                      write even if the new data shrank by more than 50%
//
// Exit codes: 0 ok (or unchanged), 1 failure or, with -check, drift, 2 usage.
package main

import (
	"bytes"
	"context"
	"errors"
	"flag"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/chainseer-xyz/deckard/internal/check/dns/takeover"
	"github.com/chainseer-xyz/deckard/internal/refdata"
	"github.com/chainseer-xyz/deckard/internal/scope"
)

const yamlHeader = "# Generated by cmd/refdata-snapshot from " + takeover.CommunityURL + "; do not edit.\n" +
	"# Refreshed entries are merged under the hand-curated fingerprints.yaml, which wins on provider-name conflicts.\n"

// Sanity floors: a source returning less than this is treated as broken.
const (
	minTakeover = 10
	minShared   = 20
)

func main() {
	os.Exit(run(context.Background(), os.Args[1:], os.Stdout, os.Stderr, nil))
}

type options struct {
	only        string
	takeoverOut string
	sharedOut   string
	timeout     time.Duration
	check       bool
	force       bool
}

// run is main with injectable I/O; client nil uses the default transport.
func run(ctx context.Context, args []string, stdout, stderr io.Writer, client *http.Client) int {
	var o options
	fs := flag.NewFlagSet("refdata-snapshot", flag.ContinueOnError)
	fs.SetOutput(stderr)
	fs.StringVar(&o.only, "only", "all", "takeover, shared or all")
	fs.StringVar(&o.takeoverOut, "takeover-out", "internal/check/dns/takeover/fingerprints_community.yaml", "takeover snapshot file")
	fs.StringVar(&o.sharedOut, "shared-out", "internal/scope/shared_cidrs_snapshot.txt", "shared ranges snapshot file")
	fs.DurationVar(&o.timeout, "timeout", 30*time.Second, "per-request timeout")
	fs.BoolVar(&o.check, "check", false, "write nothing; exit 1 if a file would change")
	fs.BoolVar(&o.force, "force", false, "write even if the data shrank by more than 50%")
	if err := fs.Parse(args); err != nil {
		return 2
	}
	if o.only != "all" && o.only != "takeover" && o.only != "shared" {
		_, _ = fmt.Fprintf(stderr, "refdata-snapshot: -only must be takeover, shared or all (got %q)\n", o.only)
		return 2
	}
	f := &refdata.Fetcher{Client: client, Timeout: o.timeout, UserAgent: "deckard-refdata-snapshot"}
	var errs []error
	drift := false
	step := func(name string, count func([]byte) int, gen func() (path string, content []byte, n int, err error)) {
		path, content, n, err := gen()
		if err != nil {
			errs = append(errs, fmt.Errorf("%s: %w", name, err))
			return
		}
		changed, err := write(path, content, o, n, count)
		switch {
		case err != nil:
			errs = append(errs, fmt.Errorf("%s: %w", name, err))
		case changed && o.check:
			drift = true
			_, _ = fmt.Fprintf(stdout, "%s: %s is out of date (%d entries)\n", name, path, n)
		case changed:
			_, _ = fmt.Fprintf(stdout, "%s: wrote %s (%d entries)\n", name, path, n)
		default:
			_, _ = fmt.Fprintf(stdout, "%s: %s unchanged (%d entries)\n", name, path, n)
		}
	}
	if o.only != "shared" {
		step("takeover", countProviders, func() (string, []byte, int, error) { return takeoverSnapshot(ctx, f, o) })
	}
	if o.only != "takeover" {
		step("shared", countLines, func() (string, []byte, int, error) { return sharedSnapshot(ctx, f, o) })
	}
	if len(errs) > 0 {
		_, _ = fmt.Fprintln(stderr, "refdata-snapshot:", errors.Join(errs...))
		return 1
	}
	if drift {
		return 1
	}
	return 0
}

func takeoverSnapshot(ctx context.Context, f *refdata.Fetcher, o options) (string, []byte, int, error) {
	got, err := f.Get(ctx, takeover.CommunityURL, refdata.Validators{})
	if err != nil {
		return "", nil, 0, err
	}
	fps, err := takeover.ConvertCommunity(got.Body)
	if err != nil {
		return "", nil, 0, err
	}
	if len(fps) < minTakeover {
		return "", nil, 0, fmt.Errorf("only %d usable fingerprints (need %d): refusing to snapshot", len(fps), minTakeover)
	}
	b, err := takeover.Marshal(fps)
	if err != nil {
		return "", nil, 0, err
	}
	return o.takeoverOut, append([]byte(yamlHeader), b...), len(fps), nil
}

func sharedSnapshot(ctx context.Context, f *refdata.Fetcher, o options) (string, []byte, int, error) {
	bodies := map[string][]byte{}
	for _, u := range scope.SharedSourceURLs {
		got, err := f.Get(ctx, u, refdata.Validators{})
		if err != nil {
			return "", nil, 0, err // a snapshot needs every source
		}
		bodies[u] = got.Body
	}
	ls, err := scope.ParseSharedSources(bodies)
	if err != nil {
		return "", nil, 0, err
	}
	if len(ls) < minShared {
		return "", nil, 0, fmt.Errorf("only %d usable ranges (need %d): refusing to snapshot", len(ls), minShared)
	}
	return o.sharedOut, scope.FormatSharedSnapshot(ls), len(ls), nil
}

// write replaces path with content if it differs, atomically. It refuses a
// snapshot that shrank by more than half versus the existing file unless forced.
func write(path string, content []byte, o options, n int, count func([]byte) int) (bool, error) {
	old, err := os.ReadFile(path) // #nosec G304 -- operator/CI supplied output path
	if err != nil && !errors.Is(err, os.ErrNotExist) {
		return false, err
	}
	if bytes.Equal(old, content) {
		return false, nil
	}
	if prev := count(old); prev > 0 && n*2 < prev && !o.force {
		return false, fmt.Errorf("%s shrank from %d to %d entries (use -force if intended)", path, prev, n)
	}
	if o.check {
		return true, nil
	}
	tmp, err := os.CreateTemp(filepath.Dir(path), ".snapshot-*.tmp")
	if err != nil {
		return false, err
	}
	name := tmp.Name()
	_, werr := tmp.Write(content)
	if cerr := tmp.Close(); werr == nil {
		werr = cerr
	}
	if werr == nil {
		werr = os.Chmod(name, 0o644) // #nosec G302 -- checked-in source file, no secrets
	}
	if werr == nil {
		werr = os.Rename(name, path)
	}
	if werr != nil {
		_ = os.Remove(name)
		return false, werr
	}
	return true, nil
}

// countProviders counts the entries of a takeover snapshot.
func countProviders(b []byte) int {
	return strings.Count(string(b), "\n- provider:") + btoi(strings.HasPrefix(string(b), "- provider:"))
}

// countLines counts the CIDR lines of a shared-ranges snapshot.
func countLines(b []byte) int {
	n := 0
	for _, l := range strings.Split(string(b), "\n") {
		if l = strings.TrimSpace(l); l != "" && !strings.HasPrefix(l, "#") {
			n++
		}
	}
	return n
}

func btoi(b bool) int {
	if b {
		return 1
	}
	return 0
}
