package main

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/chainseer-xyz/deckard/internal/check/dns/takeover"
)

type replay map[string]string // "host/path" -> body ("" = 503)

func (r replay) RoundTrip(req *http.Request) (*http.Response, error) {
	body, ok := r[req.URL.Host+req.URL.Path]
	code := http.StatusOK
	switch {
	case !ok:
		code = http.StatusNotFound
	case body == "":
		code = http.StatusNotFound
	}
	return &http.Response{StatusCode: code, Header: http.Header{}, Body: io.NopCloser(strings.NewReader(body)), Request: req}, nil
}

func read(t *testing.T, p string) string {
	t.Helper()
	b, err := os.ReadFile(p)
	if err != nil {
		t.Fatal(err)
	}
	return string(b)
}

func fixtures(t *testing.T) replay {
	t.Helper()
	sc := "../../internal/scope/testdata/"
	return replay{
		"www.cloudflare.com/ips-v4":              read(t, sc+"cloudflare-ips-v4.txt"),
		"www.cloudflare.com/ips-v6":              read(t, sc+"cloudflare-ips-v6.txt"),
		"ip-ranges.amazonaws.com/ip-ranges.json": read(t, sc+"aws-ip-ranges.json"),
		"api.fastly.com/public-ip-list":          read(t, sc+"fastly-public-ip-list.json"),
		"api.github.com/meta":                    read(t, sc+"github-meta.json"),
		"raw.githubusercontent.com/EdOverflow/can-i-take-over-xyz/master/fingerprints.json": read(t, "../../internal/check/dns/takeover/testdata/community_fingerprints.json"),
	}
}

func invoke(t *testing.T, rp replay, args ...string) (int, string, string) {
	t.Helper()
	var out, errb bytes.Buffer
	code := run(context.Background(), args, &out, &errb, &http.Client{Transport: rp})
	return code, out.String(), errb.String()
}

func TestGenerateWritesLoadableSnapshots(t *testing.T) {
	dir := t.TempDir()
	tk, sh := filepath.Join(dir, "fp.yaml"), filepath.Join(dir, "shared.txt")
	code, out, errs := invoke(t, fixtures(t), "-takeover-out", tk, "-shared-out", sh)
	if code != 0 {
		t.Fatalf("code=%d out=%s err=%s", code, out, errs)
	}
	fps, err := takeover.Load([]byte(read(t, tk)))
	if err != nil || len(fps) < 10 {
		t.Fatalf("takeover snapshot: %d entries, %v", len(fps), err)
	}
	if !strings.HasPrefix(read(t, tk), "# Generated by cmd/refdata-snapshot") || !strings.HasPrefix(read(t, sh), "# Generated by cmd/refdata-snapshot") {
		t.Error("missing generated-file header")
	}
	s := read(t, sh)
	for _, want := range []string{"52.219.170.0/23 aws-s3", "120.52.22.96/27 aws-cloudfront", "3.2.58.0/24 aws-globalaccelerator", "151.101.0.0/16 fastly", "2606:4700::/32 cloudflare"} {
		if !strings.Contains(s, want) {
			t.Errorf("shared snapshot lacks %q", want)
		}
	}
	for _, never := range []string{"35.180.0.0/16", "15.190.244.0/22"} {
		if strings.Contains(s, never) {
			t.Errorf("%s (EC2/AMAZON) must never be snapshotted as shared", never)
		}
	}

	// Rerun: unchanged; -check passes. Then drift is detected.
	if code, out, _ := invoke(t, fixtures(t), "-takeover-out", tk, "-shared-out", sh, "-check"); code != 0 || !strings.Contains(out, "unchanged") {
		t.Errorf("check on fresh files: %d %s", code, out)
	}
	if err := os.WriteFile(sh, []byte(read(t, sh)+"198.51.100.0/24 x\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	if code, _, _ := invoke(t, fixtures(t), "-takeover-out", tk, "-shared-out", sh, "-check"); code != 1 {
		t.Errorf("drift must exit 1, got %d", code)
	}
	if !strings.Contains(read(t, sh), "198.51.100.0/24") {
		t.Error("-check must not write")
	}
}

func TestSourceFailureWritesNothing(t *testing.T) {
	dir := t.TempDir()
	sh := filepath.Join(dir, "shared.txt")
	rp := fixtures(t)
	rp["api.fastly.com/public-ip-list"] = "" // 404
	code, _, errs := invoke(t, rp, "-only", "shared", "-shared-out", sh)
	if code != 1 || !strings.Contains(errs, "shared") {
		t.Fatalf("code=%d err=%s", code, errs)
	}
	if _, err := os.Stat(sh); !os.IsNotExist(err) {
		t.Error("a failed run must not write a partial snapshot")
	}
}

func TestShrinkGuardAndForce(t *testing.T) {
	dir := t.TempDir()
	tk := filepath.Join(dir, "fp.yaml")
	var big strings.Builder
	for i := 0; i < 200; i++ {
		big.WriteString("- provider: P\n  cname: ['x$']\n  nxdomain: true\n  status: vulnerable\n")
	}
	if err := os.WriteFile(tk, []byte(big.String()), 0o600); err != nil {
		t.Fatal(err)
	}
	code, _, errs := invoke(t, fixtures(t), "-only", "takeover", "-takeover-out", tk)
	if code != 1 || !strings.Contains(errs, "shrank") {
		t.Fatalf("code=%d err=%s", code, errs)
	}
	if code, _, errs := invoke(t, fixtures(t), "-only", "takeover", "-takeover-out", tk, "-force"); code != 0 {
		t.Fatalf("force: %d %s", code, errs)
	}
}

func TestBrokenSourcesRefused(t *testing.T) {
	dir := t.TempDir()
	for name, body := range map[string]string{"empty list": "[]", "garbage": "<html>", "one entry": `[{"service":"X","status":"Vulnerable","cname":["a.b"],"fingerprint":"abcdefghij"}]`} {
		rp := fixtures(t)
		rp["raw.githubusercontent.com/EdOverflow/can-i-take-over-xyz/master/fingerprints.json"] = body
		out := filepath.Join(dir, strings.ReplaceAll(name, " ", "_"))
		if code, _, _ := invoke(t, rp, "-only", "takeover", "-takeover-out", out); code != 1 {
			t.Errorf("%s: code %d", name, code)
		}
		if _, err := os.Stat(out); !os.IsNotExist(err) {
			t.Errorf("%s: wrote a file", name)
		}
	}
}

func TestUsageErrors(t *testing.T) {
	if code, _, _ := invoke(t, fixtures(t), "-only", "nope"); code != 2 {
		t.Errorf("bad -only: %d", code)
	}
	if code, _, _ := invoke(t, fixtures(t), "-bogus"); code != 2 {
		t.Errorf("bad flag: %d", code)
	}
}
